#!/bin/bash

export DOTFILES_PATH="$(dirname "$(readlink "$HOME/.bashrc")")"

# identify OS
IS_WIN=false;
IS_UNIX=false;
IS_MAC=false;

unameOut="$(uname -s)"
case "${unameOut}" in
    Linux*)     IS_UNIX=true;;
    Darwin*)    IS_MAC=true;;
    CYGWIN*)    IS_WIN=true;;
    MINGW*)     IS_WIN=true;;
    *)          machine="UNKNOWN:${unameOut}"
esac

export IS_WIN
export IS_UNIX
export IS_MAC

# function to DRY
sourceFiles() {
    for f in ${DOTFILES_PATH}/customizations/$1*.sh; do
        if [ -f "$f" ]; then
            source "$f"
        fi
    done
}

# load default customizations
sourceFiles ""


# load windows specific files
if [ "$IS_WIN" = true ]; then
    sourceFiles "windows/"
fi


# load UNIX/Server specific files
if [ "$IS_UNIX" = true ]; then
    sourceFiles "linux/"
fi


# load MAC specific files
if [ "$IS_UNIX" = true ]; then
    sourceFiles "mac/"
fi
