require("plugins.nvim-web-devicons")
require("plugins.img-clip")
require("plugins.snacks")
require("plugins.oil")
require("plugins.neo-tree")
require("plugins.fugitive")
require("plugins.code-diff")
require("plugins.gitsigns")
