dictionaries = [
  "en_us",
  "pt_br",
  "de",
]

ignore_paths = [
  "**/*.log",
  "**/package-lock.json",
  "**/yarn.lock",
  "**/pnpm-lock.yaml",
  "**/pnpm-workspace.yaml",
]

words = [
  "agentic",
  "brandkit",
  "brandkits",
  "formik",
  "keychron",
  "personio",
  "selectables",
  "whitelabel",
  "bufnr",
  "builtins",
  "codeigniter",
  "darcula",
  "disqus",
  "elif",
  "extmark",
  "extmarks",
  "folke",
  "gitsigns",
  "importmap",
  "intelephense",
  "keymap",
  "neotree",
  "neovim",
  "nvim",
  "nvimtools",
  "octo",
  "ollama",
  "opencode",
  "parloa",
  "portainer",
  "posthog",
  "shada",
  "supabase",
  "testid",
  "undercurl",
  "veed",
  "veedstudio",
  "windscribe",
  "winid",
  "zustand",
]
